### ISSUE TITLE
Computational Time

### ISSUE THREAD

**Issue by yljblues** [ethz-privsec/diffusion_denoised_smoothing#1]
Thank you for sharing the code! I'm interesting at the time cost for the experiments in this paper.

The paper says:

> We obtain a throughput of 825 images per second ... on an A100 GPU at a batch size of 1,000 (for CIFAR10)

> The overall latency of this joint denoise-then-classify model is 1.5 seconds per image on an A100 GPU at a batch size of 32 ... (for ImageNet).

If I understand correctly, for CIFAR10 with $N=100000$, it takes $100000 / 825 \approx 121$ seconds to certify a single image, and $336$ hours for the whole test set of $10000$ images on a single A100. Correspondingly for ImageNet with $N=10000$, it takes $1.5 * 10000 / 32 \approx 469$ seconds to certify a single image, and $130$ hours for $1000$ images in the test set.

I run the code with a V100 and spend 10 minutes for certifying one image of CIFAR10. It increases the difficulty to replicate the result. I guess I might need to replace the ViT with more lightweight model like WideResNet to reduce the budget.

**Comment by Eric-mingjie** [comment]
> If I understand correctly, for CIFAR10 with $N=100000$, it takes $100000 / 825 \approx 121$ seconds to certify a single image, and $336$ hours for the whole test set of $10000$ images on a single A100. Correspondingly for ImageNet with $N=10000$, it takes $1.5 * 10000 / 32 \approx 469$ seconds to certify a single image, and $130$ hours for $1000$ images in the test set.

This is correct. The ViT model we used for CIFAR-10 takes input as $224\times224$ ([here](https://github.com/ethz-privsec/diffusion_denoised_smoothing/blob/main/cifar10/DRM.py#L59)), which is the main runtime bottleneck.You can use the pretrained wideresnet from [robustbench](https://github.com/RobustBench/robustbench/blob/master/model_info/cifar10/corruptions/Standard.json). 

Thanks for your interest in our work. Please let me know if you have further questions.

**Comment by yljblues** [comment]
Thanks for your reply :)
